# Generated by Django 4.1 on 2022-08-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcgis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arcgis',
        ),
    ]
