from telegram.ext import ConversationHandler


ASK_FOR_FEEDBACK_STATE, GET_FEEDBACK_STATE = range(2)
END_FEEDBACK_STATE = ConversationHandler.END

POSITIVE_ANSWER_BUTTON = 'POSITIVE_ANSWER'
NEGATIVE_ANSWER_BUTTON = 'NEGATIVE_ANSWER'
ASK_FOR_DETAILED_FEEDBACK_BUTTON = 'ASK_FOR_DETAILED_FEEDBACK'
