# Generated by Django 3.2.6 on 2021-08-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('strategy_id', models.CharField(
                    blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('created_at', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('command_id', models.BigAutoField(
                    primary_key=True, serialize=False)),
                ('command_name', models.CharField(
                    blank=True, max_length=32, null=True)),
                ('user_id', models.PositiveBigIntegerField()),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveBigIntegerField(
                    primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(
                    blank=True, max_length=256, null=True)),
                ('language_code', models.CharField(blank=True,
                 help_text="Telegram client's lang", max_length=8, null=True)),
                ('deep_link', models.CharField(blank=True, max_length=64, null=True)),
                ('is_blocked_bot', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('subscriptions', models.ManyToManyField(
                    to='tgbot.Subscription', blank=True))
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('created_at', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('update_id', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=4096)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='tgbot.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricCandle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('open_price', models.DecimalField(decimal_places=9, max_digits=18)),
                ('high_price', models.DecimalField(decimal_places=9, max_digits=18)),
                ('low_price', models.DecimalField(decimal_places=9, max_digits=18)),
                ('close_price', models.DecimalField(decimal_places=9, max_digits=18)),
                ('volume', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('figi', models.CharField(blank=True, max_length=32, null=True)),
                ('interval', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovingAverage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('figi', models.CharField(blank=True, max_length=32, null=True)),
                ('date_time', models.DateTimeField()),
                ('period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('figi', models.CharField(blank=True, max_length=32, null=True)),
                ('ticker', models.CharField(blank=True, max_length=32, null=True)),
                ('class_code', models.CharField(blank=True, max_length=32, null=True)),
                ('isin', models.CharField(blank=True, max_length=32, null=True)),
                ('lot', models.IntegerField(default=1)),
                ('currency', models.CharField(blank=True, max_length=32, null=True)),
                ('klong', models.DecimalField(decimal_places=9, max_digits=18)),
                ('kshort', models.DecimalField(decimal_places=9, max_digits=18)),
                ('dlong', models.DecimalField(decimal_places=9, max_digits=18)),
                ('dshort', models.DecimalField(decimal_places=9, max_digits=18)),
                ('dlong_min', models.DecimalField(decimal_places=9, max_digits=18)),
                ('dshort_min', models.DecimalField(decimal_places=9, max_digits=18)),
                ('short_enabled_flag', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('exchange', models.CharField(blank=True, max_length=32, null=True)),
                ('ipo_date', models.DateTimeField()),
                ('issue_size', models.IntegerField()),
                ('country_of_risk', models.CharField(blank=True, max_length=32, null=True)),
                ('country_of_risk_name', models.CharField(blank=True, max_length=32, null=True)),
                ('sector', models.CharField(blank=True, max_length=32, null=True)),
                ('issue_size_plan', models.IntegerField()),
                ('trading_status', models.IntegerField()),
                ('otc_flag', models.BooleanField(default=False)),
                ('buy_available_flag', models.BooleanField(default=False)),
                ('sell_available_flag', models.BooleanField(default=False)),
                ('div_yield_flag', models.BooleanField(default=False)),
                ('share_type', models.IntegerField()),
                ('min_price_increment', models.DecimalField(decimal_places=16, max_digits=32)),
                ('api_trade_available_flag', models.BooleanField(default=False)),
                ('position_uid', models.CharField(blank=True, max_length=32, null=True)),
                ('for_iis_flag', models.BooleanField(default=False)),
                ('first_1min_candle_date', models.DateTimeField()),
                ('first_1day_candle_date', models.DateTimeField()),
            ],
        )
    ]
