# Generated by Django 4.1 on 2022-08-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='command',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='commands',
            field=models.ManyToManyField(blank=True, to='tgbot.command'),
        ),
        migrations.AlterField(
            model_name='feedbackmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tgbot.user'),
        ),
        migrations.AlterField(
            model_name='historiccandle',
            name='figi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='tgbot.share'),
        ),
        migrations.AlterField(
            model_name='historiccandle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historiccandle',
            name='interval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='share',
            name='figi',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='share',
            name='uid',
            field=models.CharField(max_length=32),
        ),
    ]
