# Generated by Django 4.1 on 2022-08-21 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovingAverage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('figi', models.CharField(blank=True, max_length=32, null=True)),
                ('date_time', models.DateTimeField()),
                ('period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('uid', models.CharField(max_length=32)),
                ('figi', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('ticker', models.CharField(blank=True, max_length=32, null=True)),
                ('class_code', models.CharField(blank=True, max_length=32, null=True)),
                ('isin', models.CharField(blank=True, max_length=32, null=True)),
                ('lot', models.IntegerField(default=1)),
                ('currency', models.CharField(blank=True, max_length=32, null=True)),
                ('klong', models.DecimalField(decimal_places=9, max_digits=18)),
                ('kshort', models.DecimalField(decimal_places=9, max_digits=18)),
                ('dlong', models.DecimalField(decimal_places=9, max_digits=18)),
                ('dshort', models.DecimalField(decimal_places=9, max_digits=18)),
                ('dlong_min', models.DecimalField(decimal_places=9, max_digits=18)),
                ('dshort_min', models.DecimalField(decimal_places=9, max_digits=18)),
                ('short_enabled_flag', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('exchange', models.CharField(blank=True, max_length=32, null=True)),
                ('ipo_date', models.DateTimeField()),
                ('issue_size', models.IntegerField()),
                ('country_of_risk', models.CharField(blank=True, max_length=32, null=True)),
                ('country_of_risk_name', models.CharField(blank=True, max_length=32, null=True)),
                ('sector', models.CharField(blank=True, max_length=32, null=True)),
                ('issue_size_plan', models.IntegerField()),
                ('trading_status', models.IntegerField()),
                ('otc_flag', models.BooleanField(default=False)),
                ('buy_available_flag', models.BooleanField(default=False)),
                ('sell_available_flag', models.BooleanField(default=False)),
                ('div_yield_flag', models.BooleanField(default=False)),
                ('share_type', models.IntegerField()),
                ('min_price_increment', models.DecimalField(decimal_places=16, max_digits=32)),
                ('api_trade_available_flag', models.BooleanField(default=False)),
                ('position_uid', models.CharField(blank=True, max_length=32, null=True)),
                ('for_iis_flag', models.BooleanField(default=False)),
                ('first_1min_candle_date', models.DateTimeField()),
                ('first_1day_candle_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='command',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='command',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='commands',
            field=models.ManyToManyField(blank=True, to='tgbot.command'),
        ),
        migrations.AlterField(
            model_name='feedbackmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tgbot.user'),
        ),
        migrations.CreateModel(
            name='HistoricCandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.DecimalField(decimal_places=9, max_digits=18)),
                ('high_price', models.DecimalField(decimal_places=9, max_digits=18)),
                ('low_price', models.DecimalField(decimal_places=9, max_digits=18)),
                ('close_price', models.DecimalField(decimal_places=9, max_digits=18)),
                ('volume', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('interval', models.IntegerField()),
                ('share', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tgbot.share')),
            ],
        ),
    ]
