# Generated by Django 4.1 on 2022-08-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='command',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='commands',
            field=models.ManyToManyField(blank=True, to='tgbot.command'),
        ),
    ]
