# Generated by Django 3.2.13 on 2022-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('command_id', models.CharField(blank=True, max_length=32, null=True)),
                ('number_of_calls', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='commands',
            field=models.ManyToManyField(blank=True, to='tgbot.Command'),
        ),
    ]
