# Generated by Django 4.0.6 on 2022-08-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricCandle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('open_price', models.DecimalField(decimal_places=16, max_digits=32)),
                ('high_price', models.DecimalField(decimal_places=16, max_digits=32)),
                ('low_price', models.DecimalField(decimal_places=16, max_digits=32)),
                ('close_price', models.DecimalField(decimal_places=16, max_digits=32)),
                ('volume', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('figi', models.CharField(blank=True, max_length=32, null=True)),
                ('interval', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovingAverage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('figi', models.CharField(blank=True, max_length=32, null=True)),
                ('date_time', models.DateTimeField()),
                ('window', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('figi', models.CharField(blank=True, max_length=32, null=True)),
                ('ticker', models.CharField(blank=True, max_length=32, null=True)),
                ('class_code', models.CharField(blank=True, max_length=32, null=True)),
                ('isin', models.CharField(blank=True, max_length=32, null=True)),
                ('lot', models.IntegerField(default=1)),
                ('currency', models.CharField(blank=True, max_length=32, null=True)),
                ('klong', models.DecimalField(decimal_places=16, max_digits=32)),
                ('kshort', models.DecimalField(decimal_places=16, max_digits=32)),
                ('dlong', models.DecimalField(decimal_places=16, max_digits=32)),
                ('dshort', models.DecimalField(decimal_places=16, max_digits=32)),
                ('dlong_min', models.DecimalField(decimal_places=16, max_digits=32)),
                ('dshort_min', models.DecimalField(decimal_places=16, max_digits=32)),
                ('short_enabled_flag', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('exchange', models.CharField(blank=True, max_length=32, null=True)),
                ('ipo_date', models.DateTimeField()),
                ('issue_size', models.IntegerField()),
                ('country_of_risk', models.CharField(blank=True, max_length=32, null=True)),
                ('country_of_risk_name', models.CharField(blank=True, max_length=32, null=True)),
                ('sector', models.CharField(blank=True, max_length=32, null=True)),
                ('issue_size_plan', models.IntegerField()),
                ('trading_status', models.IntegerField()),
                ('otc_flag', models.BooleanField(default=False)),
                ('buy_available_flag', models.BooleanField(default=False)),
                ('sell_available_flag', models.BooleanField(default=False)),
                ('div_yield_flag', models.BooleanField(default=False)),
                ('share_type', models.IntegerField()),
                ('min_price_increment', models.DecimalField(decimal_places=16, max_digits=32)),
                ('api_trade_available_flag', models.BooleanField(default=False)),
                ('position_uid', models.CharField(blank=True, max_length=32, null=True)),
                ('for_iis_flag', models.BooleanField(default=False)),
                ('first_1min_candle_date', models.DateTimeField()),
                ('first_1day_candle_date', models.DateTimeField()),
            ],
        ),
    ]
