# Generated by Django 4.1 on 2022-08-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_historiccandle_movingaverage_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movingaverage',
            old_name='window',
            new_name='period',
        ),
    ]
