# Generated by Django 3.2.13 on 2022-06-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_auto_20220626_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
