# Generated by Django 4.1 on 2022-08-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_remove_command_user_id_remove_command_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='figi',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
