# Generated by Django 4.1 on 2022-08-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcgis', '0002_delete_arcgis'),
        ('tgbot', '0003_rename_window_movingaverage_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
