# Generated by Django 3.2.13 on 2022-06-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_command_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='number_of_calls',
            field=models.IntegerField(default=0),
        ),
    ]
