# Generated by Django 4.1 on 2022-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_alter_share_figi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiccandle',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
