# Generated by Django 3.2.13 on 2022-06-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_feedbackmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmessage',
            old_name='message_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='feedbackmessage',
            old_name='sender_id',
            new_name='user',
        ),
    ]
