# Generated by Django 3.2.13 on 2022-06-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_auto_20220617_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategySubscription',
            fields=[
                ('created_at', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('subscription_id', models.BigAutoField(
                    primary_key=True, serialize=False)),
                ('strategy_id', models.CharField(
                    blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('subscription', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='tgbot.strategysubscription')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='tgbot.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
