# Generated by Django 3.2.13 on 2022-06-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_strategysubscription_usersubscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmessage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
