# Generated by Django 4.1 on 2022-08-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_alter_historiccandle_candle_figi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiccandle',
            old_name='candle_figi',
            new_name='share',
        ),
    ]
