# Generated by Django 3.2.13 on 2022-06-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_auto_20220618_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubscriptions',
            new_name='UserSubscription',
        ),
    ]
